### ISSUE TITLE
Defining default values for register fields has no effect.

### ISSUE THREAD

**Issue by m-kru** [wzab/agwb#12]
Following xml definition has no effect in terms of default values.

```
<creg name="CONFIG">                                                                                                                                                                                        
     <field name="RX_WIDEBUS_MODE" width="1" default="0x0"/>                                                                                                                                                   
     <field name="INIT_VALUE" width="20" default="0x0"/>                                                                                                                                                        
</creg>
```

**Comment by wzab** [comment]
It seems, that currently it works only on the register level, not on the bitfields level. So you may do

    <creg name="CONFIG" default="0x0">                                                                                                                                                                                        
       <field name="RX_WIDEBUS_MODE" width="1" />                                                                                                                                                   
       <field name="INIT_VALUE" width="20" />                                                                                                                                                        
    </creg>

but you can't define defaults for the bitfields. It must be checked if that can be easily modified.

**Comment by wzab** [comment]
The default values for bitfields are supported after commit https://github.com/wzab/addr_gen_wb/commit/41c202387d7c9190b36c335a10249c90c4724419
