### ISSUE TITLE
Block without registers

### ISSUE THREAD

**Issue by gumaas** [wzab/agwb#4]
An instantiation of a block that doesn't contain a status or control register causes the program to fail.

Example xml:

```
<sysdef top="main">

  <block name="b1">
    <creg   name="placeholder" desc="dummy"/>
  </block>

  <block name="main">
    <!-- <sreg   name="p2laceholder" desc="dummy"/> -->
    <subblock name="b1" type="b1"/>
  </block>


</sysdef>
```

The program works fine when the comment is removed.

**Comment by wzab** [comment]
The problem was fixed by adding initial empty templates for 'signal_ports' and 'signals_idle' in commit https://github.com/wzab/addr_gen_wb/commit/c04c090dd96bfef7fb1053ae8ec38f5d16b88f08
